# Dockerfile.client
FROM python:3.8-slim-bullseye

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY servidor_nivel.py .

CMD ["python", "-u", "servidor_nivel.py"]